spring:
  application:
    name: grpc
  jpa:
    defer-datasource-initialization: true
  grpc:
    server:
      inprocess:
        name: grpc-springboot
    client:
      default-channel:
        target: in-process:grpc-springboot
        negotiation-type: plaintext

  server:
    port: 8080
    http2:
      enabled: true

#  grpc:
#    server:
#      port: 6565